#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=Baseline_WB
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=6:00:00
#SBATCH --output=./slurms/baselinemodel_bcos_waterbird_%A.out

module purge
module load 2022
module load Anaconda3/2022.05
source activate FACTifAI

python train.py --model_backbone bcos --dataset WATERBIRDS --learning_rate 1e-5 --train_batch_size 64 --total_epochs 350 --save_path ./WBBASE3 --log_path ./WBbl3

